---
title: "Statistical Modeling in R"
output: html_document
---
[**Return to rwrks homepage**](http://srvanderplas.github.io/rwrks/)

The course will be a mix of instruction and follow-up exercises. It will be held in a computer lab but you are encouraged to bring your own laptops, with software already loaded. A list of software is available to help you prepare your machine for the workshop.

After the end of Statistical Modeling in R, we expect you to be able to do the following:

+ Fit models (linear regression, anova, mixed models, generalized linear mixed models)
+ Test hypotheses
+ Create model output tables and plots

**Note:** This workshop day is not a substitute for courses such as 801 and 802 which teach ANOVA, regression, some experimental design, etc. The goal is to teach you how to implement these models in R and extract and display the output; we will not be teaching experimental design or the statistical details of each test and model.

## Timetable

Time | Notes | Lectures and Resources
---- | ---- | ----
9:00 - 9:15 | [Introduction to Statistical Modeling](knitr/1-ModelingIntro.html) |  Why is statistical modeling important? Why should you do exploratory data analysis (EDA)? <br/> [1-ModelingIntro.R](code/1-ModelingIntro.R)
9:15 - 10:00 | [Basic Statistical Tests](knitr/2-BasicStatisticalTests.html) |  p-values, confidence intervals, t-tests, and chi-square tests, simple regression, etc. <br/> [2-BasicStatisticalTests.R](code/2-BasicStatisticalTests.R)
10:00 - 10:15 | **Break** | 
10:15 - 12:00 | [Linear Models (and more)](knitr/3-LinearModels.html) | ANOVA, factorials, blocking, and normality assumptions <br/> [3-LinearModels.R](code/3-LinearModels.R)
12:00 - 1:00 | **Lunch Break (on your own)** | 
1:00 - 2:15 | [Generalized Linear Models (and more)](knitr/4-GeneralizedLinearModels.html) | What if my data is not normally distributed? <br/>[4-GeneralizedLinearModels.R](code/4-GeneralizedLinearModels.R)
2:15 - 2:30 | **Break** |
2:30 - 4:00 | [Workshop: Bring Your Own Data](knitr/5-ModelingWorkshop.html) | Combine all the new R skills you learned this week to analyze your own data and walk away with results! Bonus - incorporate them into your Shiny app from yesterday! <br/>[5-ModelingWorkshop.R](code/5-ModelingWorkshop.R) <br/> *Note: We will have a few data sets if you need one.*

## Useful Links

+ [emmeans](https://cran.r-project.org/web/packages/emmeans/) - See links to Vignettes
+ [Mixed Models by Ben Bolker](https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html)
