---
title: "Graphics with ggplot2"
output: html_document
---

The course will be a mix of instruction and follow-up exercises. It will be held in a computer lab but you are encouraged to bring your own laptops, with software already loaded. A list of software is available to help you prepare your machine for the workshop.

After the end of Graphics with ggplot, we expect you to be able to do the following:

+ Visualize data in the ggplot2 package: do basic plots, as well as know about the layer system, and be able to structure complex graphics
+ Take a data set and use static graphics to look for interesting features.
+ Know about some aspects of human perception and what to avoid when plotting data.

## Timetable

Date | Notes | Lectures and Resources
---- | ---- | ----
9 - 10:30 | [Look at that!](knitr/1-GraphicsIntro.html) | basic plots: scatterplots, boxplots, histograms, barcharts and more, some aesthetics: color, shape, ... <br/> [1-GraphicsIntro.R](code/1-GraphicsIntro.R)<br/> [ggplot2 cheat sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-visualization.pdf)
10:30 - 11:30 | [Basics](knitr/2-Basics.html) | Making maps using ggplot2. <br/> [2-Basics.R](code/2-Basics.R)
11:30 - 12:30 | **Lunch Break** | 
12:30 - 2:00 | [Layers of Graphics](knitr/3-Layers.html) |  	More detailed look at the ggplot2 package: layers, geoms. <br/>[3-Layers.R](code/3-Layers.R) <br/>[noaa.rdata](data/noaa.rdata) <br/>[animal.csv](data/animal.csv)
2:00 - 2:30 | [What do we see?](knitr/4-Perception.html) |  	Discussion of faceting and cognitive aspects of human perception. <br/>[4-Perception.R](code/4-Perception.R) <br/>[frame.csv](data/frame.csv) <br/>[MovieSummary.csv](data/MovieSummary.csv)
2:30 - 3:00 | [Polishing your plots](knitr/5-PolishingPlots.html) |  	Finishing touches: options, themes. <br/>[5-PolishingPlots.R](code/5-PolishingPlots.R)

## Useful Links
Recommended Reading:

- [R for Data Science](https://r4ds.had.co.nz/) 
- [R for ecologists](https://datacarpentry.org/R-ecology-lesson/) 
+ Data Carpentry workshop 